# Generated by Django 3.0.3 on 2020-10-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0015_auto_20200331_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('quant', models.CharField(max_length=10)),
            ],
        ),
    ]
